apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: feuerwehr-db
  namespace: feuerwehr
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-ei-fj
        secretsPath: /feuerwehr
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  managedKubeSecretReferences:
    - secretName: feuerwehr-db
      secretNamespace: feuerwehr
      secretType: Opaque
  resyncInterval: 60
